name: naf_local_enc_1
num_iter: 5000
img_size: [256, 256]
kernel_size: [21, 21]
dataset: levin
save_frequency: 100
gpu: 1

network_x:
  type: NAFNetLocal
  train_size: [1, 8, 256, 256]
  in_channel: 8
  out_channel: 1
  width: 32
  middle_blk_num: 1
  enc_blk_nums: [1, 1, 1, 1]
  dec_blk_nums: [1, 1, 1, 1]

network_k:
  type: FCN
  num_input_channels: 200
  num_output_channels: 441
  num_hidden: 1000

train:
  optim:
    type: AdamW
    lr: !!float 1e-3
    ker_lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]